package foodwaste.domain;
// Generated May 1, 2017 2:32:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Areofinterest generated by hbm2java
 */
public class Areofinterest  implements java.io.Serializable {


     private int intareaid;
     private String interestarea;
     private Set users = new HashSet(0);

    public Areofinterest() {
    }

	
    public Areofinterest(int intareaid, String interestarea) {
        this.intareaid = intareaid;
        this.interestarea = interestarea;
    }
    public Areofinterest(int intareaid, String interestarea, Set users) {
       this.intareaid = intareaid;
       this.interestarea = interestarea;
       this.users = users;
    }
   
    public int getIntareaid() {
        return this.intareaid;
    }
    
    public void setIntareaid(int intareaid) {
        this.intareaid = intareaid;
    }
    public String getInterestarea() {
        return this.interestarea;
    }
    
    public void setInterestarea(String interestarea) {
        this.interestarea = interestarea;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


