package foodwaste.domain;
// Generated May 1, 2017 2:32:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Compgroup generated by hbm2java
 */
public class Compgroup  implements java.io.Serializable {


     private int compgroupid;
     private String compgroup;
     private Set compsubgroups = new HashSet(0);

    public Compgroup() {
    }

    public Compgroup(int compgroupid, String compgroup) {
        this.compgroupid = compgroupid;
        this.compgroup = compgroup;
    }

	
     public Compgroup(int compgroupid, String compgroup, Set compsubgroups) {
       this.compgroupid = compgroupid;
       this.compgroup = compgroup;
       this.compsubgroups = compsubgroups;
    }
   
    public int getCompgroupid() {
        return this.compgroupid;
    }
    
    public void setCompgroupid(int compgroupid) {
        this.compgroupid = compgroupid;
    }
    public String getCompgroup() {
        return this.compgroup;
    }
    
    public void setCompgroup(String compgroup) {
        this.compgroup = compgroup;
    }
    public Set getCompsubgroups() {
        return this.compsubgroups;
    }
    
    public void setCompsubgroups(Set compsubgroups) {
        this.compsubgroups = compsubgroups;
    }




}


