package foodwaste.domain;
// Generated May 1, 2017 2:32:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Compsubgroup generated by hbm2java
 */
public class Compsubgroup  implements java.io.Serializable {


     private int compsubgroupid;
     private Compgroup compgroup;
     private String compsubgroup;
     private Set components = new HashSet(0);

    public Compsubgroup() {
    }

    public Compsubgroup(int compsubgroupid, String compsubgroup) {
        this.compsubgroupid = compsubgroupid;
        this.compsubgroup = compsubgroup;
    }

	
    public Compsubgroup(int compsubgroupid, Compgroup compgroup, String compsubgroup) {
        this.compsubgroupid = compsubgroupid;
        this.compgroup = compgroup;
        this.compsubgroup = compsubgroup;
    }
    public Compsubgroup(int compsubgroupid, Compgroup compgroup, String compsubgroup, Set components) {
       this.compsubgroupid = compsubgroupid;
       this.compgroup = compgroup;
       this.compsubgroup = compsubgroup;
       this.components = components;
    }
   
    public int getCompsubgroupid() {
        return this.compsubgroupid;
    }
    
    public void setCompsubgroupid(int compsubgroupid) {
        this.compsubgroupid = compsubgroupid;
    }
    public Compgroup getCompgroup() {
        return this.compgroup;
    }
    
    public void setCompgroup(Compgroup compgroup) {
        this.compgroup = compgroup;
    }
    public String getCompsubgroup() {
        return this.compsubgroup;
    }
    
    public void setCompsubgroup(String compsubgroup) {
        this.compsubgroup = compsubgroup;
    }
    public Set getComponents() {
        return this.components;
    }
    
    public void setComponents(Set components) {
        this.components = components;
    }




}


