package foodwaste.domain;
// Generated May 1, 2017 2:32:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fcdb generated by hbm2java
 */
public class Fcdb  implements java.io.Serializable {


     private int fcdbid;
     private String version;
     private Country country;
     private String fcdbdesc;
     private Set foods = new HashSet(0);

    public Fcdb() {
    }

	
    public Fcdb(int fcdbid, Country country) {
        this.fcdbid = fcdbid;
        this.country = country;
    }
    public Fcdb(int fcdbid, Country country, String fcdbdesc, Set foods) {
       this.fcdbid = fcdbid;
       this.country = country;
       this.fcdbdesc = fcdbdesc;
       this.foods = foods;
    }
   
    public int getFcdbid() {
        return this.fcdbid;
    }
    
    public void setFcdbid(int fcdbid) {
        this.fcdbid = fcdbid;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public String getFcdbdesc() {
        return this.fcdbdesc;
    }
    
    public void setFcdbdesc(String fcdbdesc) {
        this.fcdbdesc = fcdbdesc;
    }
    public Set getFoods() {
        return this.foods;
    }
    
    public void setFoods(Set foods) {
        this.foods = foods;
    }




}


