package foodwaste.domain;
// Generated May 1, 2017 2:32:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Food generated by hbm2java
 */
public class Food  implements java.io.Serializable {


     private int foodid;
     private Fcdb fcdb;
     private String foodname;
     private String origfoodcode;
     private Set wastestreams = new HashSet(0);
     private String remark;
    public Food() {
    }

	
    public Food(int foodid, String foodname) {
        this.foodid = foodid;
        this.foodname = foodname;
    }
    public Food(int foodid, Fcdb fcdb, String foodname, String origfoodcode, Set wastestreams) {
       this.foodid = foodid;
       this.fcdb = fcdb;
       this.foodname = foodname;
       this.origfoodcode = origfoodcode;
       this.wastestreams = wastestreams;
    }

    public Food(int foodid, String foodname, String origfoodcode) {
        this.foodid = foodid;
        this.foodname = foodname;
        this.origfoodcode = origfoodcode;
    }
   
    public int getFoodid() {
        return this.foodid;
    }
    
    public void setFoodid(int foodid) {
        this.foodid = foodid;
    }
    public Fcdb getFcdb() {
        return this.fcdb;
    }
    
    public void setFcdb(Fcdb fcdb) {
        this.fcdb = fcdb;
    }
    public String getFoodname() {
        return this.foodname;
    }
    
    public void setFoodname(String foodname) {
        this.foodname = foodname;
    }
    public String getOrigfoodcode() {
        return this.origfoodcode;
    }
    
    public void setOrigfoodcode(String origfoodcode) {
        this.origfoodcode = origfoodcode;
    }
    public Set getWastestreams() {
        return this.wastestreams;
    }
    
    public void setWastestreams(Set wastestreams) {
        this.wastestreams = wastestreams;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }




}


