package foodwaste.domain;
// Generated May 1, 2017 2:32:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Institution generated by hbm2java
 */
public class Institution  implements java.io.Serializable {


     private int instid;
     private Country country;
     private Institutiontype institutiontype;
     private String insname;
     private Set users = new HashSet(0);

    public Institution() {
    }

	
    public Institution(int instid, Country country, Institutiontype institutiontype, String insname) {
        this.instid = instid;
        this.country = country;
        this.institutiontype = institutiontype;
        this.insname = insname;
    }
    public Institution(int instid, Country country, Institutiontype institutiontype, String insname, Set users) {
       this.instid = instid;
       this.country = country;
       this.institutiontype = institutiontype;
       this.insname = insname;
       this.users = users;
    }
   
    public int getInstid() {
        return this.instid;
    }
    
    public void setInstid(int instid) {
        this.instid = instid;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public Institutiontype getInstitutiontype() {
        return this.institutiontype;
    }
    
    public void setInstitutiontype(Institutiontype institutiontype) {
        this.institutiontype = institutiontype;
    }
    public String getInsname() {
        return this.insname;
    }
    
    public void setInsname(String insname) {
        this.insname = insname;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


