package foodwaste.domain;
// Generated May 1, 2017 2:32:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Reference generated by hbm2java
 */
public class Reference  implements java.io.Serializable {


     private int refid;
     private Referencetype referencetype;
     private int wsid;
     private String srcode;
     private String citation;
     private Set wsvalues = new HashSet(0);

    public Reference() {
    }

    public Reference(int refid, String srcode, String citation) {
        this.refid = refid;
        this.srcode = srcode;
        this.citation = citation;
    }

	
    public Reference(int refid, Referencetype referencetype, int wsid) {
        this.refid = refid;
        this.referencetype = referencetype;
        this.wsid = wsid;
    }
    public Reference(int refid, Referencetype referencetype, int wsid, String srcode, String citation, Set wsvalues) {
       this.refid = refid;
       this.referencetype = referencetype;
       this.wsid = wsid;
       this.srcode = srcode;
       this.citation = citation;
       this.wsvalues = wsvalues;
    }
   
    public int getRefid() {
        return this.refid;
    }
    
    public void setRefid(int refid) {
        this.refid = refid;
    }
    public Referencetype getReferencetype() {
        return this.referencetype;
    }
    
    public void setReferencetype(Referencetype referencetype) {
        this.referencetype = referencetype;
    }
    public int getWsid() {
        return this.wsid;
    }
    
    public void setWsid(int wsid) {
        this.wsid = wsid;
    }
    public String getSrcode() {
        return this.srcode;
    }
    
    public void setSrcode(String srcode) {
        this.srcode = srcode;
    }
    public String getCitation() {
        return this.citation;
    }
    
    public void setCitation(String citation) {
        this.citation = citation;
    }
    public Set getWsvalues() {
        return this.wsvalues;
    }
    
    public void setWsvalues(Set wsvalues) {
        this.wsvalues = wsvalues;
    }




}


