package foodwaste.domain;
// Generated May 1, 2017 2:32:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private int roleid;
     private String roledesc;
     private Set users = new HashSet(0);

    public Role() {
    }

	
    public Role(int roleid, String roledesc) {
        this.roleid = roleid;
        this.roledesc = roledesc;
    }
    public Role(int roleid, String roledesc, Set users) {
       this.roleid = roleid;
       this.roledesc = roledesc;
       this.users = users;
    }
   
    public int getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(int roleid) {
        this.roleid = roleid;
    }
    public String getRoledesc() {
        return this.roledesc;
    }
    
    public void setRoledesc(String roledesc) {
        this.roledesc = roledesc;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


