package foodwaste.domain;
// Generated May 1, 2017 2:32:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Searchstatistics generated by hbm2java
 */
public class Searchstatistics  implements java.io.Serializable {


     private int userid;
     private User user;
     private Wastestream wastestream;
     private String searchkeyword;
     private Date datetime;

    public Searchstatistics() {
    }

    public Searchstatistics(User user, Wastestream wastestream, String searchkeyword, Date datetime) {
       this.user = user;
       this.wastestream = wastestream;
       this.searchkeyword = searchkeyword;
       this.datetime = datetime;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Wastestream getWastestream() {
        return this.wastestream;
    }
    
    public void setWastestream(Wastestream wastestream) {
        this.wastestream = wastestream;
    }
    public String getSearchkeyword() {
        return this.searchkeyword;
    }
    
    public void setSearchkeyword(String searchkeyword) {
        this.searchkeyword = searchkeyword;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }




}


