package foodwaste.domain;
// Generated May 1, 2017 2:32:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Unit generated by hbm2java
 */
public class Unit  implements java.io.Serializable {


     private int unitid;
     private String ftc;
     private String term;
     private String bt;
     private String sn;
     private String ai;
     private String classification;
     private String active;
     private Date dateupdated;
     private Date datecreated;
     private String updatecomment;
     private int single;
     private Set wsvalues = new HashSet(0);

    public Unit() {
    }

	
    public Unit(int unitid, String ftc, String term, String bt, String sn, String ai, String classification, String active, Date dateupdated, Date datecreated, String updatecomment, int single) {
        this.unitid = unitid;
        this.ftc = ftc;
        this.term = term;
        this.bt = bt;
        this.sn = sn;
        this.ai = ai;
        this.classification = classification;
        this.active = active;
        this.dateupdated = dateupdated;
        this.datecreated = datecreated;
        this.updatecomment = updatecomment;
        this.single = single;
    }
    public Unit(int unitid, String ftc, String term, String bt, String sn, String ai, String classification, String active, Date dateupdated, Date datecreated, String updatecomment, int single, Set wsvalues) {
       this.unitid = unitid;
       this.ftc = ftc;
       this.term = term;
       this.bt = bt;
       this.sn = sn;
       this.ai = ai;
       this.classification = classification;
       this.active = active;
       this.dateupdated = dateupdated;
       this.datecreated = datecreated;
       this.updatecomment = updatecomment;
       this.single = single;
       this.wsvalues = wsvalues;
    }
   
    public int getUnitid() {
        return this.unitid;
    }
    
    public void setUnitid(int unitid) {
        this.unitid = unitid;
    }
    public String getFtc() {
        return this.ftc;
    }
    
    public void setFtc(String ftc) {
        this.ftc = ftc;
    }
    public String getTerm() {
        return this.term;
    }
    
    public void setTerm(String term) {
        this.term = term;
    }
    public String getBt() {
        return this.bt;
    }
    
    public void setBt(String bt) {
        this.bt = bt;
    }
    public String getSn() {
        return this.sn;
    }
    
    public void setSn(String sn) {
        this.sn = sn;
    }
    public String getAi() {
        return this.ai;
    }
    
    public void setAi(String ai) {
        this.ai = ai;
    }
    public String getClassification() {
        return this.classification;
    }
    
    public void setClassification(String classification) {
        this.classification = classification;
    }
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
    public Date getDateupdated() {
        return this.dateupdated;
    }
    
    public void setDateupdated(Date dateupdated) {
        this.dateupdated = dateupdated;
    }
    public Date getDatecreated() {
        return this.datecreated;
    }
    
    public void setDatecreated(Date datecreated) {
        this.datecreated = datecreated;
    }
    public String getUpdatecomment() {
        return this.updatecomment;
    }
    
    public void setUpdatecomment(String updatecomment) {
        this.updatecomment = updatecomment;
    }
    public int getSingle() {
        return this.single;
    }
    
    public void setSingle(int single) {
        this.single = single;
    }
    public Set getWsvalues() {
        return this.wsvalues;
    }
    
    public void setWsvalues(Set wsvalues) {
        this.wsvalues = wsvalues;
    }




}


