package foodwaste.domain;
// Generated May 1, 2017 2:32:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int userid;
     private Areofinterest areofinterest;
     private Institution institution;
     private Role role;
     private String name;
     private String surname;
     private String email;
     private String password;
     private Set priorities = new HashSet(0);
     private Searchstatistics searchstatistics;
     private Set wsvalues = new HashSet(0);
private String verificationToken;
     private String enabled;
     private Date expireTime;

    public User() {
    }

    public User(String email, String password) {
        this.email = email;
        this.password = password;
    }

    public User(int userid, String name, String surname, String email) {
        this.userid = userid;
        this.name = name;
        this.surname = surname;
        this.email = email;
    }

	
    public User(int userid, Areofinterest areofinterest, Institution institution, Role role, String name, String surname, String email, String password) {
        this.userid = userid;
        this.areofinterest = areofinterest;
        this.institution = institution;
        this.role = role;
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.password = password;
    }
    public User(int userid, Areofinterest areofinterest, Institution institution, Role role, String name, String surname, String email, String password, Set priorities, Searchstatistics searchstatistics, Set wsvalues) {
       this.userid = userid;
       this.areofinterest = areofinterest;
       this.institution = institution;
       this.role = role;
       this.name = name;
       this.surname = surname;
       this.email = email;
       this.password = password;
       this.priorities = priorities;
       this.searchstatistics = searchstatistics;
       this.wsvalues = wsvalues;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public Areofinterest getAreofinterest() {
        return this.areofinterest;
    }
    
    public void setAreofinterest(Areofinterest areofinterest) {
        this.areofinterest = areofinterest;
    }
    public Institution getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(Institution institution) {
        this.institution = institution;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getPriorities() {
        return this.priorities;
    }
    
    public void setPriorities(Set priorities) {
        this.priorities = priorities;
    }
    public Searchstatistics getSearchstatistics() {
        return this.searchstatistics;
    }
    
    public void setSearchstatistics(Searchstatistics searchstatistics) {
        this.searchstatistics = searchstatistics;
    }
    public Set getWsvalues() {
        return this.wsvalues;
    }
    
    public void setWsvalues(Set wsvalues) {
        this.wsvalues = wsvalues;
    }

public String getVerificationToken() {
        return verificationToken;
    }

    public void setVerificationToken(String verificationToken) {
        this.verificationToken = verificationToken;
    }

    public String getEnabled() {
        return enabled;
    }

    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }

    public Date getExpireTime() {
        return expireTime;
    }

    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }



}


