package foodwaste.domain;
// Generated May 1, 2017 2:32:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Wastestream generated by hbm2java
 */
public class Wastestream  implements java.io.Serializable {


     private int wsid;
     private Food food;
     private String wastestream;
     private String wsdesc;
     private String foodex2;
     private Double edible;
     private Double specgravity;
     private Double ncf;
     private Double gcf;
     private String remark;
     private Set wsvalues = new HashSet(0);
     private Set priorities = new HashSet(0);
     private Set searchstatisticses = new HashSet(0);

    public Wastestream() {
    }

    public Wastestream(int wsid, String wastestream, String wsdesc, String foodex2, Double edible, Double specgravity, Double ncf, Double gcf, String remark) {
        this.wsid = wsid;
        this.wastestream = wastestream;
        this.wsdesc = wsdesc;
        this.foodex2 = foodex2;
        this.edible = edible;
        this.specgravity = specgravity;
        this.ncf = ncf;
        this.gcf = gcf;
        this.remark = remark;
    }

	
    public Wastestream(int wsid, Food food, String wastestream, String foodex2, String remark) {
        this.wsid = wsid;
        this.food = food;
        this.wastestream = wastestream;
        this.foodex2 = foodex2;
        this.remark = remark;
    }
    public Wastestream(int wsid, Food food, String wastestream, String wsdesc, String foodex2, Double edible, Double specgravity, Double ncf, Double gcf, String remark, Set wsvalues, Set priorities, Set searchstatisticses) {
       this.wsid = wsid;
       this.food = food;
       this.wastestream = wastestream;
       this.wsdesc = wsdesc;
       this.foodex2 = foodex2;
       this.edible = edible;
       this.specgravity = specgravity;
       this.ncf = ncf;
       this.gcf = gcf;
       this.remark = remark;
       this.wsvalues = wsvalues;
       this.priorities = priorities;
       this.searchstatisticses = searchstatisticses;
    }
   
    public int getWsid() {
        return this.wsid;
    }
    
    public void setWsid(int wsid) {
        this.wsid = wsid;
    }
    public Food getFood() {
        return this.food;
    }
    
    public void setFood(Food food) {
        this.food = food;
    }
    public String getWastestream() {
        return this.wastestream;
    }
    
    public void setWastestream(String wastestream) {
        this.wastestream = wastestream;
    }
    public String getWsdesc() {
        return this.wsdesc;
    }
    
    public void setWsdesc(String wsdesc) {
        this.wsdesc = wsdesc;
    }
    public String getFoodex2() {
        return this.foodex2;
    }
    
    public void setFoodex2(String foodex2) {
        this.foodex2 = foodex2;
    }
    public Double getEdible() {
        return this.edible;
    }
    
    public void setEdible(Double edible) {
        this.edible = edible;
    }
    public Double getSpecgravity() {
        return this.specgravity;
    }
    
    public void setSpecgravity(Double specgravity) {
        this.specgravity = specgravity;
    }
    public Double getNcf() {
        return this.ncf;
    }
    
    public void setNcf(Double ncf) {
        this.ncf = ncf;
    }
    public Double getGcf() {
        return this.gcf;
    }
    
    public void setGcf(Double gcf) {
        this.gcf = gcf;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Set getWsvalues() {
        return this.wsvalues;
    }
    
    public void setWsvalues(Set wsvalues) {
        this.wsvalues = wsvalues;
    }
    public Set getPriorities() {
        return this.priorities;
    }
    
    public void setPriorities(Set priorities) {
        this.priorities = priorities;
    }
    public Set getSearchstatisticses() {
        return this.searchstatisticses;
    }
    
    public void setSearchstatisticses(Set searchstatisticses) {
        this.searchstatisticses = searchstatisticses;
    }




}


