package foodwaste.domain;
// Generated May 1, 2017 2:32:57 PM by Hibernate Tools 4.3.1



/**
 * Wsvalue generated by hbm2java
 */
public class Wsvalue  implements java.io.Serializable {


     private int valueid;
     private Acquisitiontype acquisitiontype;
     private Component component;
     private Matrix matrix;
     private Methodindicator methodindicator;
     private Methodtype methodtype;
     private Reference reference;
     private Unit unit;
     private User user;
     private Valuetype valuetype;
     private Wastestream wastestream;
     private Double value;
     private String remark;
     private String checked;
    public Wsvalue() {
    }

	
    public Wsvalue(int valueid, Acquisitiontype acquisitiontype, Component component, Matrix matrix, Methodindicator methodindicator, Methodtype methodtype, Reference reference, Unit unit, User user, Valuetype valuetype, Wastestream wastestream) {
        this.valueid = valueid;
        this.acquisitiontype = acquisitiontype;
        this.component = component;
        this.matrix = matrix;
        this.methodindicator = methodindicator;
        this.methodtype = methodtype;
        this.reference = reference;
        this.unit = unit;
        this.user = user;
        this.valuetype = valuetype;
        this.wastestream = wastestream;
    }
    public Wsvalue(int valueid, Acquisitiontype acquisitiontype, Component component, Matrix matrix, Methodindicator methodindicator, Methodtype methodtype, Reference reference, Unit unit, User user, Valuetype valuetype, Wastestream wastestream, Double value, String remark) {
       this.valueid = valueid;
       this.acquisitiontype = acquisitiontype;
       this.component = component;
       this.matrix = matrix;
       this.methodindicator = methodindicator;
       this.methodtype = methodtype;
       this.reference = reference;
       this.unit = unit;
       this.user = user;
       this.valuetype = valuetype;
       this.wastestream = wastestream;
       this.value = value;
       this.remark = remark;
    }
   
    public int getValueid() {
        return this.valueid;
    }
    
    public void setValueid(int valueid) {
        this.valueid = valueid;
    }
    public Acquisitiontype getAcquisitiontype() {
        return this.acquisitiontype;
    }
    
    public void setAcquisitiontype(Acquisitiontype acquisitiontype) {
        this.acquisitiontype = acquisitiontype;
    }
    public Component getComponent() {
        return this.component;
    }
    
    public void setComponent(Component component) {
        this.component = component;
    }
    public Matrix getMatrix() {
        return this.matrix;
    }
    
    public void setMatrix(Matrix matrix) {
        this.matrix = matrix;
    }
    public Methodindicator getMethodindicator() {
        return this.methodindicator;
    }
    
    public void setMethodindicator(Methodindicator methodindicator) {
        this.methodindicator = methodindicator;
    }
    public Methodtype getMethodtype() {
        return this.methodtype;
    }
    
    public void setMethodtype(Methodtype methodtype) {
        this.methodtype = methodtype;
    }
    public Reference getReference() {
        return this.reference;
    }
    
    public void setReference(Reference reference) {
        this.reference = reference;
    }
    public Unit getUnit() {
        return this.unit;
    }
    
    public void setUnit(Unit unit) {
        this.unit = unit;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Valuetype getValuetype() {
        return this.valuetype;
    }
    
    public void setValuetype(Valuetype valuetype) {
        this.valuetype = valuetype;
    }
    public Wastestream getWastestream() {
        return this.wastestream;
    }
    
    public void setWastestream(Wastestream wastestream) {
        this.wastestream = wastestream;
    }
    public Double getValue() {
        return this.value;
    }
    
    public void setValue(Double value) {
        this.value = value;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getChecked() {
        return checked;
    }

    public void setChecked(String checked) {
        this.checked = checked;
    }




}


